[project]
name = "mcp-sv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]==1.6.0",
    "ipykernel",
    "jupyter",
    "neo4j",
    "matplotlib>=3.10.5",
    "networkx>=3.5",
    "pandas>=2.3.1",
]
